### ISSUE TITLE
Follow ASP.NET Core guidance for Web

### ISSUE THREAD

**Issue by rafsanulhasan** [dotnet-architecture/eShopOnWeb#131]
@ardalis IMHO, we should follow ASP.NET Core docs, guidance and best practices for the Web:
- [x] Update ASP.NET Core to 2.1.4 (done in PR #136) 
- [x] Add HTTPS Endpoints (done in PR #127)
- [x] Add GDPR Cookie Compliance support (check user's consent to use Cookie) (done in PR #130)
- [x] Update Docker images for the following: (done in PR #129)
  - [x] ASP.NET Core Runtime 2.2.103
  - [x] .NET Core SDK 2.2
- [ ] Update Readme.md and Docs (*.epubs and *.pdf under docs)

**N.B** These PRs are  needed to be merged respectively.

**Comment by ardalis** [comment]
Updated a bunch of these recently; will get the last shortly.

**Comment by ardalis** [comment]
Updated by https://github.com/dotnet-architecture/eShopOnWeb/commit/88835916d8ab4ab2dc33173e8d5a4d92dace2d48

**Comment by ardalis** [comment]
README and docs updates are coming soon as soon as the new eBook is reviewed. Closing this now.
